project_name: wave

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}'

release:
  draft: true

changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
