name: Ship

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Semver tag
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GORELEASER_CURRENT_TAG: ${{ github.event.inputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
        with:
          deno-version: 1.9

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Generate Release Notes
        run: deno run -A https://deno.land/x/ghlog/ghlog.ts ${{ github.repository }} -v '${{ github.event.inputs.tag }}'

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist

      - name: Release v${{ github.event.inputs.tag }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: '${{ github.event.inputs.tag }}'
          name: 'v${{ github.event.inputs.tag }}'
          bodyFile: 'CHANGELOG.md'
          artifacts: 'dist/*.zip,dist/checksums.txt'
          draft: true
